version: 2.0
jobs:
  build:
    environment:
      CC_TEST_REPORTER_ID: YOUR_REPO_CC_TEST_REPORTER_ID
    docker:
      - image: circleci/php:7.1.9-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - run: echo " A first hello"
